site_name: "Multi-Tenancy March Workshop"
site_url: "https://LoftLabs-Experiments.github.io/workshop-shared-platfrom-stack/"
theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "light blue"
nav:
  - Home: index.md
  - Workshop Guide: workshop.md

