name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Build and Deploy
        run: mkdocs gh-deploy --force

